//
// Created by Mirzokhid on 11/28/2025.
//

#ifndef FRESHMAN_1STSEMESTER_PROJECT_COMPUTER_PROGRAMMING_DECOMPRESS_LZSS_H
#define FRESHMAN_1STSEMESTER_PROJECT_COMPUTER_PROGRAMMING_DECOMPRESS_LZSS_H

#include <fstream>

void Decompress_LZSS(std::ifstream& file);

#endif // FRESHMAN_1STSEMESTER_PROJECT_COMPUTER_PROGRAMMING_DECOMPRESS_LZSS_H
